tasks
netology-code/pb-homeworks pull request #11
Opened 2018-11-01 08:51 UTC by dualex23

2018-11-02 22:51 UTC, nlopin requested changes

2018-11-02 22:51 UTC, nlopin commented on 2.1 arrays/readme.md
> +Пользователь отправляет на форум сообщения и нам нужно где-то их хранить. Для этого создайте массив и сохраните в нем сообщения в том порядке, в котором они приведены:
Форум у нас в третьем блоке. Здесь мессенджер

2018-11-02 22:51 UTC, nlopin commented on 2.1 arrays/readme.md
> +В прошлом задании мы удалили запись по индексу, но программа должна работать автоматически. Для этого нужно находить индекс удаляемого сообщения автоматически. Запишите сообщение, которое желает удал
Два раза «автоматически» в двух предложения подряд. Давай как-нибудь переформулируем

2018-11-11 10:57 UTC, dualex23 commented
edit 2.2

2018-11-11 11:00 UTC, closed without merging