1.1 Базовые понятия. Переменные и числа
netology-code/pb-homeworks pull request #2
Opened 2018-09-17 08:41 UTC by dualex23

2018-09-18 07:12 UTC, igorkamyshev commented on README.md
> +[1.1. Базовые понятия. Переменные и числа](https://github.com/dualex23/pb-homeworks/tree/master/variables)
Лучше использовать относительные пути. Сейчас путь строго завязан на конкретный репозиторий конкретного пользователя, что не очень хорошо.

2018-09-18 07:24 UTC, igorkamyshev commented on variables/readme.md
> +## Инструкция по выполнению домашнего задания
Три решетки, чтобы не нарушать структуру документа.

2018-09-18 07:24 UTC, igorkamyshev commented on variables/readme.md
> +1. Переходим по ссылке на repl.it
Неконсистентное отношение с повелительным наклонением. Иногда "присылаем", иногда "прислать".

2018-09-18 16:30 UTC, nlopin commented on variables/readme.md
> +### Повторить
Этот блок вообще не показываем студентам

2018-09-18 16:40 UTC, nlopin requested changes

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +### Шаги по решению задачи
Процесс реализации

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +### Повторить
тоже убираем

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +### Повторить
Убираем

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +:::info
info вроде бы никак не отображается особенно, достаточно курсива

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +1) Создайте две переменные username и reputation
Нужно выделить имена переменных и значения обратными кавычками, чтобы появилась подсветка `username` и `reputation`

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +В мессенджере у каждого есть имя и репутация. В мессенджер зашел Лев Толстой. Нам нужно отобразить ему информацию об успешном входе и его репутации.
Нам нужно отобразить → Отобразите (чтобы во всех задачах одинаково повелительное наклонение было)

2018-09-18 16:40 UTC, nlopin commented on variables/readme.md
> +**Посчитайте** прогноз репутации на 10 дней вперед для Льва Толстого, если обычно он редактирует одно сообщение раз в два дня.
В других задачах не выделено, а тут выделено

2018-09-18 16:42 UTC, nlopin commented
@dualex23 проверь еще на всякий случай структуру. Она должна совпадать со структурой [домашки на ветвеление](https://github.com/netology-code/pb-homeworks/tree/master/boolean)

2018-09-19 09:01 UTC, nlopin requested changes
Осталась пара мелочей по тексту

2018-09-19 09:01 UTC, nlopin commented on variables/readme.md
> +2. Создайте переменную штрафы за редактирование отправленного сообщения.
штрафы → со штрафом

2018-09-19 09:01 UTC, nlopin commented on variables/readme.md
> +4. Учтите очки репутации, которые списываются(штрафы) с пользователя за редактирование сообщения.
Может (штрафы) передвинуть к словам «очки репутации»?

2018-09-19 09:03 UTC, merged

2018-09-19 16:57 UTC, dualex23 commented on variables/readme.md
> +4. Учтите очки репутации, которые списываются(штрафы) с пользователя за редактирование сообщения.
ок